### ISSUE TITLE
GamePad power/screen off on boot

### ISSUE THREAD

**Issue by filipe-maia** [Lynx64/GamepadAutoStandby#1]
Hi,

First of all, sorry, but I haven't tested your plugin yet.
I hope to find time this weekend to install Aroma on my Wii U for the first time.

I have some requests, don't know if they are good ideas or not:
1 - option to keep the game pad off when the Wii U turns on.
2 - option to keep the game pad screen off when the Wii U turns on.
3 - menu icon to immediately turn the game pad off (I've seen there is already an icon to turn the game pad on).
4 - menu icon to immediately turn the game pad screen off or on.
5 - button shortcut (configurable) to immediately turn the game pad off.
6 - button shortcut (configurable) to immediately turn the game pad screen off or on.

I don't know if this helps or not, but some of the features I mention seem to be kind of available in the plugin:
https://github.com/WiiDatabase/Padcon-Plugin-Mod
I'm opening a similar issue in the Padcon-Plugin-Mod, in case you guys find a good idea to help each other.

Thanks.

**Comment by Andrew1Hawes** [comment]
Hello, thanks for taking the time to write an issue. I have read through your same issue on the Padcon repo and pretty much share the same thoughts.

1 & 2 - I will look into this when I get the time, but it's low priority. 3 & 4 - I don't really see the point when you could just press a button combo. 5 & 6 - That is the purpose of Padcon. If you want those features, use that plugin instead/as well.

**Comment by filipe-maia** [comment]
Hello.
Thank you :)
I'm using both plugins now, and I love them. The gamepad is super comfortable on my hands, but I hate it's battery problems, so I'm always using the pro controller and I turn off the gamepad.


I'm placing the following link here just to create a connection between the two issues:
https://github.com/WiiDatabase/Padcon-Plugin-Mod/issues/10

**Comment by Andrew1Hawes** [comment]
I'm not going to bother with screen off on boot. I think basically everyone will just use power off anyway.
